export const LOCAL_SETTINGS_UPDATE_LIBRARY_PATH =
  'LOCAL_SETTINGS_UPDATE_LIBRARY_PATH';

export const PLAYTEST_TEST = 'PLAYTEST_TEST';
export const PLAYTEST_TEST_TWO = 'PLAYTEST_TEST_TWO';

export const PLAYTEST_REMOTE_STATE_LOAD_START =
  'PLAYTEST_REMOTE_STATE_LOAD_START';
export const PLAYTEST_REMOTE_STATE_SET_LIST = 'PLAYTEST_REMOTE_STATE_SET_LIST';

export const PLAYTEST_LOCAL_STATE_LOAD_START =
  'PLAYTEST_LOCAL_STATE_LOAD_START';
export const PLAYTEST_LOCAL_STATE_LOAD = 'PLAYTEST_LOCAL_STATE_LOAD';
export const PLAYTEST_LOCAL_STATE_SET_LIST_START =
  'PLAYTEST_LOCAL_STATE_SET_LIST_START';
export const PLAYTEST_LOCAL_STATE_SET_LIST = 'PLAYTEST_LOCAL_STATE_SET_LIST';

export const FTP_CONFIG_LOAD_START = 'FTP_CONFIG_LOAD_START';
export const FTP_CONFIG_LOAD_FINISH = 'FTP_CONFIG_LOAD_FINISH';
